overrides:
  glob: '>=10.5.0'

minimumReleaseAgeExclude:
  - bwh-auth

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver

allowBuilds:
  '@swc/core': true
  esbuild: true
  unrs-resolver: true
