overrides:
  glob: '>=10.5.0'

minimumReleaseAgeExclude:
  - bwh-auth

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  bwh-auth: true
  esbuild: true
  spotlight-noindex: true
  unrs-resolver: true
